# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ltxwords
version:      0.02
version_from: script/ltxwords
installdirs:  site
requires:
    Getopt::Long:                  2.1
    Lingua::EN::Numbers:           0
    Lingua::NL::Numbers::GroeneBoekje: 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
